application: jobcgae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /jobc
  script: handler.app

- url: /jobc/inviteonly/
  script: handler.app

- url: /jobc/login
  script: handler.app

- url: /jobc/logout
  script: handler.app

- url: /jobc/realjd(/(?:[a-zA-Z0-9_-]+/?)*)
  script: handler.app

- url: /jobc/realjd/_edit(/(?:[a-zA-Z0-9_-]+/?)*)
  script: handler.app

- url: /jobc/aboutus
  script: handler.app

- url: /jobc/realjob
  script: handler.app

- url: /jobc/marketing
  script: handler.app

- url: /jobc/informationtechnology
  script: handler.app

- url: /jobc/sales
  script: handler.app

- url: /jobc/finance
  script: handler.app

- url: /jobc/consulting
  script: handler.app

- url: /jobc/supplychain
  script: handler.app

- url: /static
  static_dir: static

- url: /images
  static_dir: images

libraries:
- name: jinja2
  version: latest