application: jobc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /jobc
  script: handler.app

- url: /jobc/inviteonly/
  script: handler.app

- url: /jobc/home
  script: handler.app

- url: /jobc/realjd(/(?:[a-zA-Z0-9_-]+/?)*)
  script: handler.app

- url: /jobc/realjd/_edit(/(?:[a-zA-Z0-9_-]+/?)*)
  script: handler.app

- url: /static
  static_dir: static

libraries:
- name: jinja2
  version: latest